module.exports = [
	require("./grade-1.json") ,
	require("./grade-10.json") ,
	require("./grade-11.json") ,
	require("./grade-12.json") ,
	require("./grade-2.json") ,
	require("./grade-3.json") ,
	require("./grade-4.json") ,
	require("./grade-5.json") ,
	require("./grade-6.json") ,
	require("./grade-7.json") ,
	require("./grade-8.json") ,
	require("./grade-9.json") ,
	require("./grade-k.json") ,
]
